version: '3.7'
services: 
    jupyter-pycaret:
        build: .
        container_name: pycaret
        volumes:
            - "$PWD:/home/jovyan"
        ports:
            - "8888:8888"
        command:
          jupyter-lab --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''